In [1]:
import pandas as pd
from csv_prepare import csv_import
from create_df import read_df

In [2]:
csv_import()

()

In [3]:
df = read_df()
df

,Unnamed: 0,Ablesezeitpunkt,Zaehlerstand Einheitstarif,Zaehlerstand Hochtarif,Zaehlerstand Niedertarif,Verbrauch Einheitstarif,Verbrauch Hochtarif,Verbrauch Niedertarif
0,0,2022-01-01T00:00:00.000+01:00,466.455139,0,0,4.599803,0,0
1,1,2022-01-02T00:00:00.000+01:00,471.054932,0,0,4.599803,0,0
2,2,2022-01-03T00:00:00.000+01:00,475.654724,0,0,4.599802,0,0
3,3,2022-01-04T00:00:00.000+01:00,480.254547,0,0,4.599803,0,0
4,4,2022-01-05T00:00:00.000+01:00,484.85434,0,0,4.599803,0,0
...,...,...,...,...,...,...,...,...
360,360,2022-12-27T00:00:00.000+01:00,2097.376,0,0,2.678,0,0
361,361,2022-12-28T00:00:00.000+01:00,2103.27,0,0,5.894,0,0
362,362,2022-12-29T00:00:00.000+01:00,2107.235,0,0,3.965,0,0
363,363,2022-12-30T00:00:00.000+01:00,2113.575,0,0,6.34,0,0
364,364,2022-12-31T00:00:00.000+01:00,2116.692,0,0,3.117,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 364
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  730 non-null    int64
 1   Ablesezeitpunkt             730 non-null    object
 2   Zaehlerstand Einheitstarif  730 non-null    object
 3   Zaehlerstand Hochtarif      730 non-null    int64
 4   Zaehlerstand Niedertarif    730 non-null    int64
 5   Verbrauch Einheitstarif     730 non-null    object
 6   Verbrauch Hochtarif         730 non-null    int64
 7   Verbrauch Niedertarif       730 non-null    int64
dtypes: int64(5), object(3)
memory usage: 51.3+ KB